wallpaper {
	monitor =
	path = ~/Pictures/frieren.jpg
	fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/Pictures/frieren-firework.jpeg
    fit_mode = cover
}
wallpaper {
    monitor = 
    path = ~/Pictures/frieren-crystal.jpg
    fit_mode = cover
}

splash = false
